fragment PostParts on Post {
  __typename
  title
  description
  date
  body
}

fragment PageParts on Page {
  __typename
  title
  blocks {
    __typename
    ... on PageBlocksHero {
      heading
      subheading
      actions {
        __typename
        label
        url
      }
    }
  }
}

fragment GlobalParts on Global {
  __typename
  siteTitle
  tagline
  logo
  footerContent
}
