query GetGlobalDoc {
  # references the single doc: content/global/main.mdx
  globalDocument(relativePath: "main.mdx") {
    ...MyGlobalParts
  }
}

fragment MyGlobalParts on Global {
  siteTitle
  tagline
  footerText
}
