# ------------------------------------------------
# Fragment definitions
# ------------------------------------------------

fragment UserAuthorParts on Author {
  name
  avatar
  bio
}

fragment UserPageParts on Page {
  title
  description
  body
}

fragment UserPostParts on Post {
  title
  description
  date
  excerpt
  body
}

# ------------------------------------------------
# Queries
# ------------------------------------------------

query pageQuery {
  postConnection {
    edges {
      node {
        id
        date
        title
        excerpt
        author {
          ... on Author {
            ...UserAuthorParts
          }
        }
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  page(relativePath: $relativePath) {
    ...UserPageParts
  }
}

query blogPostQuery($relativePath: String!) {
  post(relativePath: $relativePath) {
    ...UserPostParts
    author {
      ... on Author {
        ...UserAuthorParts
      }
    }
  }
}
