name: Tina Schema Push
on:
  workflow_dispatch:
    # Lets you run it manually in GitHub Actions
  push:
    branches:
      - main
jobs:
  pushSchema:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Push Tina schema
        run: pnpm tinacms schema:push
        env:
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          NEXT_PUBLIC_TINA_BRANCH: "main"
