name: Tina Cloud Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pushSchema:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Tina Cloud Build
        # This replaces the old `schema:push` command.
        run: pnpm tinacms build
        env:
          NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_TINA_CLIENT_ID }}
          TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
          # Adjust if your main branch is named differently
          NEXT_PUBLIC_TINA_BRANCH: "main"
