name: Deploy Static Site

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: |
          npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Deploy to static branch
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          # Create a new orphan branch (no history)
          git checkout --orphan temp-static

          # Remove all files from git tracking
          git rm -rf .

          # Copy contents of out directory to root
          cp -R out/* .
          rm -rf out

          # Add all files
          git add .

          # Commit with timestamp
          git commit -m "Deploy static site $(date +'%Y-%m-%d %H:%M:%S')"

          # Force push to static branch
          git push -f origin temp-static:static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}