name: Sync Content (and Schema) from Main to Staging
on:
  push:
    branches:
      - main
    paths:
      - "content/**"
      - "tina/**"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Switch to Staging and Pull Updated Content
        run: |
          git fetch origin staging
          git checkout staging
          git checkout main -- content tina
          git add content tina
          git commit -m "Sync content from main" || echo "No changes to commit"
          git push origin staging
